apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: keycloaks.k8s.keycloak.org
  labels:
    app.kubernetes.io/name: keycloak-operator
    app.kubernetes.io/instance: keycloak-operator
    app.kubernetes.io/part-of: keycloak
spec:
  group: k8s.keycloak.org
  versions:
  - name: v2alpha1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        description: Keycloak is the Schema for the keycloaks API
        type: object
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: KeycloakSpec defines the desired state of Keycloak
            type: object
            properties:
              instances:
                description: Number of Keycloak instances in HA mode
                type: integer
                default: 1
              image:
                description: Keycloak image tag
                type: string
              hostname:
                description: Hostname for the Keycloak server
                type: string
              tlsSecret:
                description: TLS Secret name
                type: string
              db:
                description: Database configuration
                type: object
                properties:
                  vendor:
                    description: Database vendor
                    type: string
                  host:
                    description: Database host
                    type: string
                  port:
                    description: Database port
                    type: integer
                  database:
                    description: Database name
                    type: string
                  usernameSecret:
                    description: Secret containing database username
                    type: object
                    properties:
                      name:
                        type: string
                      key:
                        type: string
                  passwordSecret:
                    description: Secret containing database password
                    type: object
                    properties:
                      name:
                        type: string
                      key:
                        type: string
              additionalOptions:
                description: Additional Keycloak server options
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    value:
                      type: string
          status:
            description: KeycloakStatus defines the observed state of Keycloak
            type: object
            properties:
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    lastTransitionTime:
                      type: string
                    reason:
                      type: string
                    message:
                      type: string
              ready:
                type: boolean
  scope: Namespaced
  names:
    plural: keycloaks
    singular: keycloak
    kind: Keycloak
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: keycloakrealmimports.k8s.keycloak.org
  labels:
    app.kubernetes.io/name: keycloak-operator
    app.kubernetes.io/instance: keycloak-operator
    app.kubernetes.io/part-of: keycloak
spec:
  group: k8s.keycloak.org
  versions:
  - name: v2alpha1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        description: KeycloakRealmImport is the Schema for the keycloakrealmimports API
        type: object
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            description: KeycloakRealmImportSpec defines the desired state of KeycloakRealmImport
            type: object
            properties:
              keycloakCRName:
                description: The name of the Keycloak CR to reference
                type: string
              realm:
                description: Realm representation
                type: object
                x-kubernetes-preserve-unknown-fields: true
          status:
            description: KeycloakRealmImportStatus defines the observed state of KeycloakRealmImport
            type: object
            properties:
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    lastTransitionTime:
                      type: string
                    reason:
                      type: string
                    message:
                      type: string
              ready:
                type: boolean
  scope: Namespaced
  names:
    plural: keycloakrealmimports
    singular: keycloakrealmimport
    kind: KeycloakRealmImport