apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: keycloak-operator

resources:
- namespace.yaml
- crds.yaml
- rbac.yaml
- deployment.yaml

commonLabels:
  app.kubernetes.io/name: keycloak-operator
  app.kubernetes.io/component: operator
  app.kubernetes.io/part-of: matric-platform