apiVersion: v1
kind: Namespace
metadata:
  name: keycloak-system
  labels:
    app.kubernetes.io/name: keycloak-operator
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: matric-platform