# Production external secrets configuration
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-db-secret
  namespace: keycloak-prod
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: keycloak-db-secret
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: keycloak-prod/database
      property: username
  - secretKey: password
    remoteRef:
      key: keycloak-prod/database
      property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-admin-secret
  namespace: keycloak-prod
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: keycloak-admin-secret
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: keycloak-prod/admin
      property: username
  - secretKey: password
    remoteRef:
      key: keycloak-prod/admin
      property: password
---
# Additional production secrets
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-truststore-secret
  namespace: keycloak-prod
spec:
  refreshInterval: 60s
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: keycloak-truststore-secret
    creationPolicy: Owner
  data:
  - secretKey: truststore.p12
    remoteRef:
      key: keycloak-prod/certificates
      property: truststore_p12
  - secretKey: truststore-password
    remoteRef:
      key: keycloak-prod/certificates
      property: truststore_password
---
# Production TLS certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-tls-prod
  namespace: keycloak-prod
spec:
  secretName: keycloak-tls-secret-prod
  dnsNames:
  - auth.matric.local
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  privateKey:
    algorithm: RSA
    size: 2048
  usages:
  - digital signature
  - key encipherment