services:
  postgres:
    image: postgres:15-alpine
    container_name: keycloak-postgres
    environment:
      POSTGRES_DB: ${KEYCLOAK_DB_NAME:-keycloak}
      POSTGRES_USER: ${KEYCLOAK_DB_USER:-keycloak}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD:-keycloak_dev_2024}
    ports:
      - "5433:5432"  # Different port to avoid conflicts
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - keycloak-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.2
    container_name: matric-keycloak
    command: start-dev --import-realm
    environment:
      # Bootstrap admin credentials (proper way for Keycloak 26.x)
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      # Import settings - realm import happens from data/import directory
      # Database configuration
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/${KEYCLOAK_DB_NAME:-keycloak}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER:-keycloak}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD:-keycloak_dev_2024}
      # Development settings
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      # Note: SAML cannot be disabled via features in 26.3.2
      # Security hardening will be done via realm configuration
      # Logging
      KC_LOG_LEVEL: INFO
      QUARKUS_LOG_CATEGORY__ORG_KEYCLOAK_EVENTS: DEBUG
    ports:
      - "8081:8080"  # Keycloak UI & API
      - "8787:8787"  # Debug port (optional)
    volumes:
      - keycloak_data:/opt/keycloak/data
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/realms/matric-dev"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - keycloak-network

volumes:
  postgres_data:
    name: keycloak_postgres_data
  keycloak_data:
    name: keycloak_data

networks:
  keycloak-network:
    name: keycloak_network
    driver: bridge