# Docker Compose extension for HashiCorp Vault integration
# Usage: docker-compose -f docker-compose.yml -f docker-compose.vault.yml up

version: '3.8'

services:
  vault:
    image: hashicorp/vault:1.17
    container_name: matric-vault
    restart: unless-stopped
    ports:
      - "8200:8200"  # Vault API and UI
    environment:
      # Development mode configuration
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_TOKEN:-matric-dev-root-token}
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_ADDR: ${VAULT_ADDR:-http://localhost:8200}
      VAULT_API_ADDR: ${VAULT_ADDR:-http://localhost:8200}
      # Disable mlock for development (not recommended for production)
      VAULT_DISABLE_MLOCK: "true"
      # Enable UI
      VAULT_UI: "true"
      # Logging configuration
      VAULT_LOG_LEVEL: INFO
    cap_add:
      - IPC_LOCK
    volumes:
      - vault_data:/vault/data
      - vault_logs:/vault/logs
      - ./vault/config:/vault/config:ro
      - ./vault/policies:/vault/policies:ro
    command: >
      vault server 
      -dev 
      -dev-root-token-id=matric-dev-root-token
      -dev-listen-address=0.0.0.0:8200
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - keycloak-network
    depends_on:
      keycloak:
        condition: service_healthy

  # Vault initialization service
  vault-init:
    image: hashicorp/vault:1.17
    container_name: matric-vault-init
    restart: "no"
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: matric-dev-root-token
    volumes:
      - ../scripts:/scripts:ro
    networks:
      - keycloak-network
    depends_on:
      vault:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    command: >
      sh -c "
        echo 'Waiting for Vault to be ready...'
        sleep 10
        echo 'Configuring Vault JWT authentication...'
        chmod +x /scripts/configure-vault-jwt.sh
        /scripts/configure-vault-jwt.sh
        echo 'Vault configuration completed'
      "

volumes:
  vault_data:
    name: vault_data
  vault_logs:
    name: vault_logs

# Note: Networks are inherited from the main docker-compose.yml