apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: keycloak
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: identity-provider
    app.kubernetes.io/part-of: matric-platform
data:
  # Security headers configuration
  security-headers.conf: |
    # Security Headers
    X-Frame-Options: DENY
    X-Content-Type-Options: nosniff
    X-XSS-Protection: 1; mode=block
    Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
    Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; connect-src 'self'; frame-ancestors 'none'
    Referrer-Policy: strict-origin-when-cross-origin
    Permissions-Policy: geolocation=(), microphone=(), camera=()
  
  # Keycloak server configuration
  keycloak.conf: |
    # Database configuration
    db=postgres
    db-url-host=postgres.database.svc.cluster.local
    db-url-port=5432
    db-url-database=keycloak
    db-username=${KC_DB_USERNAME}
    db-password=${KC_DB_PASSWORD}
    
    # Security configuration - SAML disabled per CVE-2024-8698
    features=oidc-identity-provider,authorization,impersonation,web-authn,scripts,token-exchange,admin-fine-grained-authz,recovery-codes,update-email,preview
    features-disabled=saml
    
    # Hostname configuration
    hostname=${KC_HOSTNAME}
    hostname-strict=true
    hostname-strict-https=true
    
    # HTTP configuration
    http-enabled=false
    https-port=8443
    
    # Proxy configuration
    proxy=edge
    
    # Metrics configuration
    metrics-enabled=true
    health-enabled=true
    
    # Cache configuration for HA
    cache=ispn
    cache-stack=kubernetes
    
    # Logging configuration
    log=console
    log-level=INFO,org.keycloak:INFO
    
    # Transaction configuration
    transaction-xa-enabled=false