apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: matric-realm-import
  namespace: keycloak
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: identity-provider
    app.kubernetes.io/part-of: matric-platform
spec:
  keycloakCRName: keycloak
  realm:
    realm: "matric"
    enabled: true
    displayName: "MATRIC Platform"
    displayNameHtml: "<div class=\"kc-logo-text\"><span>MATRIC Platform</span></div>"
    notBefore: 0
    defaultSignatureAlgorithm: "RS256"
    revokeRefreshToken: false
    refreshTokenMaxReuse: 0
    accessTokenLifespan: 300
    accessTokenLifespanForImplicitFlow: 900
    ssoSessionIdleTimeout: 1800
    ssoSessionMaxLifespan: 36000
    ssoSessionIdleTimeoutRememberMe: 0
    ssoSessionMaxLifespanRememberMe: 0
    offlineSessionIdleTimeout: 2592000
    offlineSessionMaxLifespanEnabled: false
    offlineSessionMaxLifespan: 5184000
    clientSessionIdleTimeout: 0
    clientSessionMaxLifespan: 0
    clientOfflineSessionIdleTimeout: 0
    clientOfflineSessionMaxLifespan: 0
    accessCodeLifespan: 60
    accessCodeLifespanUserAction: 300
    accessCodeLifespanLogin: 1800
    actionTokenGeneratedByAdminLifespan: 43200
    actionTokenGeneratedByUserLifespan: 300
    oauth2DeviceCodeLifespan: 600
    oauth2DevicePollingInterval: 5
    sslRequired: "external"
    registrationAllowed: false
    registrationEmailAsUsername: false
    rememberMe: true
    verifyEmail: true
    loginWithEmailAllowed: true
    duplicateEmailsAllowed: false
    resetPasswordAllowed: true
    editUsernameAllowed: false
    bruteForceProtected: true
    permanentLockout: false
    maxFailureWaitSeconds: 900
    minimumQuickLoginWaitSeconds: 60
    waitIncrementSeconds: 60
    quickLoginCheckMilliSeconds: 1000
    maxDeltaTimeSeconds: 43200
    failureFactor: 30
    passwordPolicy: "length(12) and digits(1) and lowerCase(1) and upperCase(1) and specialChars(1) and notUsername and notEmail and passwordHistory(5)"
    otpPolicyType: "totp"
    otpPolicyAlgorithm: "HmacSHA1"
    otpPolicyInitialCounter: 0
    otpPolicyDigits: 6
    otpPolicyLookAheadWindow: 1
    otpPolicyPeriod: 30
    otpPolicyCodeReusable: false
    roles:
      realm:
      - name: "admin"
        description: "Administrator role"
        composite: false
        clientRole: false
        containerId: "matric"
      - name: "user"
        description: "Standard user role"
        composite: false
        clientRole: false
        containerId: "matric"
      - name: "moderator"
        description: "Moderator role"
        composite: false
        clientRole: false
        containerId: "matric"
    groups:
    - name: "administrators"
      path: "/administrators"
      realmRoles: ["admin"]
    - name: "users"
      path: "/users"
      realmRoles: ["user"]
    - name: "moderators"
      path: "/moderators"
      realmRoles: ["moderator"]
    defaultRoles: ["user"]
    browserSecurityHeaders:
      contentSecurityPolicyReportOnly: ""
      xContentTypeOptions: "nosniff"
      xRobotsTag: "none"
      xFrameOptions: "SAMEORIGIN"
      contentSecurityPolicy: "frame-src 'self'; frame-ancestors 'self'; object-src 'none';"
      xXSSProtection: "1; mode=block"
      strictTransportSecurity: "max-age=31536000; includeSubDomains"
    eventsEnabled: true
    eventsListeners: ["jboss-logging"]
    adminEventsEnabled: true
    adminEventsDetailsEnabled: true
    internationalizationEnabled: true
    supportedLocales: ["en", "es", "fr", "de"]
    defaultLocale: "en"
    clients:
    - clientId: "matric-web-app"
      name: "MATRIC Web Application"
      description: "Main web application client"
      rootUrl: "https://app.matric.local"
      adminUrl: "https://app.matric.local"
      baseUrl: "https://app.matric.local"
      surrogateAuthRequired: false
      enabled: true
      alwaysDisplayInConsole: false
      clientAuthenticatorType: "client-secret"
      redirectUris:
      - "https://app.matric.local/*"
      - "https://app-dev.matric.local/*"
      webOrigins:
      - "https://app.matric.local"
      - "https://app-dev.matric.local"
      notBefore: 0
      bearerOnly: false
      consentRequired: false
      standardFlowEnabled: true
      implicitFlowEnabled: false
      directAccessGrantsEnabled: false
      serviceAccountsEnabled: false
      publicClient: false
      frontchannelLogout: false
      protocol: "openid-connect"
      fullScopeAllowed: true
      nodeReRegistrationTimeout: -1
      defaultClientScopes: ["web-origins", "acr", "roles", "profile", "email"]
      optionalClientScopes: ["address", "phone", "offline_access", "microprofile-jwt"]
    - clientId: "matric-api"
      name: "MATRIC API"
      description: "Backend API client for service-to-service communication"
      surrogateAuthRequired: false
      enabled: true
      alwaysDisplayInConsole: false
      clientAuthenticatorType: "client-secret"
      redirectUris: []
      webOrigins: []
      notBefore: 0
      bearerOnly: true
      consentRequired: false
      standardFlowEnabled: false
      implicitFlowEnabled: false
      directAccessGrantsEnabled: false
      serviceAccountsEnabled: true
      publicClient: false
      frontchannelLogout: false
      protocol: "openid-connect"
      fullScopeAllowed: false
      nodeReRegistrationTimeout: -1
      defaultClientScopes: ["web-origins", "acr", "roles", "profile", "email"]
      optionalClientScopes: ["address", "phone", "offline_access", "microprofile-jwt"]