# Development-specific external secrets configuration
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-db-secret
  namespace: keycloak-dev
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: keycloak-db-secret
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: keycloak-dev/database
      property: username
  - secretKey: password
    remoteRef:
      key: keycloak-dev/database
      property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-admin-secret
  namespace: keycloak-dev
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: keycloak-admin-secret
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: keycloak-dev/admin
      property: username
  - secretKey: password
    remoteRef:
      key: keycloak-dev/admin
      property: password
---
# Development TLS certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-tls-dev
  namespace: keycloak-dev
spec:
  secretName: keycloak-tls-secret-dev
  dnsNames:
  - auth-dev.matric.local
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer